$(document).ready(function(){
  $("#flip").click(function(){
    $("#panel").slideDown("slow");
  });
});
$(document).ready(function(){
  $("#panel").click(function(){
    $("#panel").slideUp("slow");
  });
});
$(document).ready(function(){
  $("#menu").click(function(){
    $("#slide").slideToggle("slow");
  });
});
$(document).ready(function(){
  $("#slide").click(function(){
    $("#slide").slideUp("slow");
  });
});